name: Override environment variables
on: push
env:
    EXAMPLE: defined by workflow level # ワークフローレベルで環境変数を定義
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${EXAMPLE}"    # ワークフローレベルの環境変数を出力
            - env:
                EXAMPLE: defined by step level # ステップレベルでの環境変数を定義
              run: echo "${EXAMPLE}" # オーバーライドされた環境変数を出力