name: Status check functions
on: push
jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 # 終了ステータスがゼロ以外なので、エラーが発生する
      - run: echo "Hello"
        if: ${{ failure() }} # ワークフロー実行IDで分岐